export const LIST_CONFIGURATION = 'LIST_CONFIGURATION';

export const ADD_SIFCOLLECTOR = 'ADD_SIFCOLLECTOR';
export const RESET_SIFCOLLECTOR = 'RESET_SIFCOLLECTOR';
export const LIST_SIFCOLLECTOR = 'LIST_SIFCOLLECTOR';
export const SET_SIFCOLLECTOR = 'SET_SIFCOLLECTOR';
export const EDIT_SIFCOLLECTOR = 'EDIT_SIFCOLLECTOR';

export const LIST_INTERVAL = 'LIST_INTERVAL';
export const LIST_SNMP = 'LIST_SNMP';

export const ADD_SENSOR = 'ADD_SENSOR';
export const SET_SENSOR = 'SET_SENSOR';
export const EDIT_SENSOR = 'EDIT_SENSOR';
export const REM_SENSOR = 'REM_SENSOR';
export const RESET_SENSOR = 'RESET_SENSOR';

export const ADD_DEVICE = 'ADD_DEVICE';
export const SET_DEVICE = 'SET_DEVICE';
export const EDIT_DEVICE = 'EDIT_DEVICE';
export const PAGE_DEVICE = 'PAGE_DEVICE';
export const RESET_DEVICE = 'RESET_DEVICE';