export const LIST_CONFIGURATION = 'LIST_CONFIGURATION';
export const SET_TABKEY = 'SET_TABKEY';

export const ADD_DEVICEPROFILECOMMUNITY = 'ADD_DEVICEPROFILECOMMUNITY';
export const RESET_DEVICEPROFILECOMMUNITY = 'RESET_DEVICEPROFILECOMMUNITY';
export const EDIT_DEVICEPROFILECOMMUNITY = 'EDIT_DEVICEPROFILECOMMUNITY';
export const LIST_DEVICEPROFILECOMMUNITY = 'LIST_DEVICEPROFILECOMMUNITY';
export const SET_DEVICEPROFILECOMMUNITY = 'SET_DEVICEPROFILECOMMUNITY';
export const REM_DEVICEPROFILECOMMUNITY = 'REM_DEVICEPROFILECOMMUNITY';

export const ADD_DEVICEAUTHPROFILE = 'ADD_DEVICEAUTHPROFILE';
export const RESET_DEVICEAUTHPROFILE = 'RESET_DEVICEAUTHPROFILE';
export const EDIT_DEVICEAUTHPROFILE = 'EDIT_DEVICEAUTHPROFILE';
export const LIST_DEVICEAUTHPROFILE = 'LIST_DEVICEAUTHPROFILE';
export const SET_DEVICEAUTHPROFILE = 'SET_DEVICEAUTHPROFILE';
export const REM_DEVICEAUTHPROFILE = 'REM_DEVICEAUTHPROFILE';

export const ADD_SIFCOLLECTOR = 'ADD_SIFCOLLECTOR';
export const RESET_SIFCOLLECTOR = 'RESET_SIFCOLLECTOR';
export const LIST_SIFCOLLECTOR = 'LIST_SIFCOLLECTOR';
export const SET_SIFCOLLECTOR = 'SET_SIFCOLLECTOR';
export const EDIT_SIFCOLLECTOR = 'EDIT_SIFCOLLECTOR';
export const REM_SIFCOLLECTOR = 'REM_SIFCOLLECTOR';

export const LIST_INTERVAL = 'LIST_INTERVAL';
export const LIST_SNMP = 'LIST_SNMP';
export const LIST_SENSORKIND = 'LIST_SENSORKIND';

export const ADD_SENSOR = 'ADD_SENSOR';
export const SET_SENSOR = 'SET_SENSOR';
export const EDIT_SENSOR = 'EDIT_SENSOR';
export const REM_SENSOR = 'REM_SENSOR';
export const RESET_SENSOR = 'RESET_SENSOR';

export const ADD_DEVICE = 'ADD_DEVICE';
export const SET_DEVICE = 'SET_DEVICE';
export const EDIT_DEVICE = 'EDIT_DEVICE';
export const PAGE_DEVICE = 'PAGE_DEVICE';
export const RESET_DEVICE = 'RESET_DEVICE';